# Generated by Django 3.2.5 on 2021-07-31 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='name of discount', max_length=100, null=True, verbose_name='name:')),
                ('amount', models.IntegerField(help_text='amount of discount', verbose_name='amount:')),
                ('unit', models.CharField(choices=[('rial', 'rial'), ('percent', 'percent')], help_text='choice unit of discount', max_length=7, verbose_name='unit:')),
            ],
            options={
                'verbose_name': 'discount',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, help_text='The number you want to price', null=True, verbose_name='amount:')),
                ('price', models.PositiveIntegerField(help_text='price of item', verbose_name='Enter price:')),
            ],
            options={
                'verbose_name': 'price',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of product', max_length=100, verbose_name='name:')),
                ('brand', models.CharField(help_text='Enter name of manufacturer', max_length=100, verbose_name='Brand:')),
                ('Inventory', models.IntegerField(help_text='Inventory of product', verbose_name='Inventory')),
                ('Category', models.ForeignKey(help_text='choose category', on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='category:')),
                ('discount', models.ForeignKey(help_text='choose discount', on_delete=django.db.models.deletion.CASCADE, to='product.discount', verbose_name='discount:')),
                ('price', models.ForeignKey(help_text='choose price', on_delete=django.db.models.deletion.CASCADE, to='product.price', verbose_name='price:')),
            ],
            options={
                'verbose_name': 'product',
            },
        ),
    ]
